FROM node:18-alpine

WORKDIR /app

# 패키지 설치에 필요한 파일 복사
COPY package.json yarn.lock ./

# 빌드에 필요한 종속성 설치
RUN yarn install --frozen-lockfile

# 프로젝트 파일 복사
COPY . .

# jest 실행을 위한 환경 설정
ENV NODE_ENV=test

# 테스트 실행 커맨드
CMD ["yarn", "test:e2e"] 