version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      args:
        APP_NAME: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - event
    networks:
      - app-network
    environment:
      - AUTH_SERVICE_HOST=auth
      - AUTH_SERVICE_PORT=3001
      - EVENT_SERVICE_HOST=event
      - EVENT_SERVICE_PORT=3002
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MONGODB_URI=${MONGODB_URI}
      - LOG_LEVEL=debug

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      args:
        APP_NAME: auth
    ports:
       - "3001:3000"
    networks:
      - app-network
    environment:
      - LOG_LEVEL=debug
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - MONGODB_URI=${MONGODB_URI}

  event:
    build:
      context: .
      dockerfile: ./apps/event/Dockerfile
      args:
        APP_NAME: event
    ports:
       - "3002:3000"
    networks:
      - app-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - LOG_LEVEL=debug

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=event-reward
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge 