version: '3.8'

services:
  # 테스트용 MongoDB 서비스
  mongodb-test:
    image: mongo:latest
    container_name: mongodb-test
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=event_reward_test
    ports:
      - "27018:27017"
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    command: mongod --wiredTigerCacheSizeGB 1.5
    networks:
      - test-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://root:password@localhost:27017/event_reward_test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  # 통합 테스트 실행 서비스
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: integration-tests
    depends_on:
      mongodb-test:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://root:password@mongodb-test:27017/event_reward_test
      - JWT_SECRET=test_secret_key
      - JWT_EXPIRATION=1h
    networks:
      - test-network
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn test:e2e

networks:
  test-network:
    driver: bridge 