version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      args:
        APP_NAME: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - event
    networks:
      - app-network
    env_file:
      - .env

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      args:
        APP_NAME: auth
    expose:
      - "3001"
    networks:
      - app-network
    env_file:
      - .env

  event:
    build:
      context: .
      dockerfile: ./apps/event/Dockerfile
      args:
        APP_NAME: event
    expose:
      - "3002"
    networks:
      - app-network
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=event-reward
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network

volumes:
  mongodb_data:
    driver: local

networks:
  app-network:
    driver: bridge 